window.DEFAULT_VOCABULARY = [
{id:'v001',ru:'идти',de:'gehen',altDe:['zu Fuß gehen'],type:'verb',topic:'Bewegung',note:'zielgerichtet, jetzt / einmal',forms:'иду = ich gehe; идёшь = du gehst; идёт = er/sie geht; идём = wir gehen; идёте = ihr/Sie geht/gehen; идут = sie gehen'},
{id:'v002',ru:'ходить',de:'gehen',altDe:['regelmäßig gehen','hin und her gehen'],type:'verb',topic:'Bewegung',note:'nicht zielgerichtet oder regelmäßig',forms:'хожу = ich gehe; ходишь = du gehst; ходит = er/sie geht; ходим = wir gehen; ходите = ihr/Sie geht/gehen; ходят = sie gehen'},
{id:'v003',ru:'пойти',de:'losgehen',altDe:['hingehen','gehen werden'],type:'verb',topic:'Bewegung',note:'vollendet; Beginn einer Bewegung zu Fuß'},
{id:'v004',ru:'ехать',de:'fahren',altDe:['mit einem Verkehrsmittel fahren'],type:'verb',topic:'Bewegung',note:'zielgerichtet, jetzt / einmal',forms:'еду = ich fahre; едешь = du fährst; едет = er/sie fährt; едем = wir fahren; едете = ihr/Sie fahrt/fahren; едут = sie fahren'},
{id:'v005',ru:'ездить',de:'fahren',altDe:['regelmäßig fahren','hin und her fahren'],type:'verb',topic:'Bewegung',note:'nicht zielgerichtet oder regelmäßig',forms:'езжу = ich fahre; ездишь = du fährst; ездит = er/sie fährt; ездим = wir fahren; ездите = ihr/Sie fahrt/fahren; ездят = sie fahren'},
{id:'v006',ru:'поехать',de:'losfahren',altDe:['hinfahren','fahren werden'],type:'verb',topic:'Bewegung',note:'vollendet; Beginn einer Fahrt'},
{id:'v007',ru:'приходить',de:'kommen',altDe:['ankommen'],type:'verb',topic:'Bewegung',note:'zu Fuß, unvollendet'},
{id:'v008',ru:'прийти',de:'kommen',altDe:['ankommen'],type:'verb',topic:'Bewegung',note:'zu Fuß, vollendet'},
{id:'v009',ru:'приезжать',de:'kommen',altDe:['ankommen','anfahren'],type:'verb',topic:'Bewegung',note:'mit Verkehrsmittel, unvollendet'},
{id:'v010',ru:'приехать',de:'kommen',altDe:['ankommen'],type:'verb',topic:'Bewegung',note:'mit Verkehrsmittel, vollendet'},
{id:'v011',ru:'плавать',de:'schwimmen',altDe:['herumschwimmen'],type:'verb',topic:'Bewegung',note:'nicht zielgerichtet oder regelmäßig'},
{id:'v012',ru:'плыть',de:'schwimmen',altDe:['schwimmen zu'],type:'verb',topic:'Bewegung',note:'zielgerichtet'},
{id:'v013',ru:'кататься',de:'fahren',altDe:['herumfahren','eine Fahrt machen','Schlittschuh laufen','Ski fahren'],type:'verb',topic:'Bewegung',note:'Freizeitbewegung; genaue Bedeutung aus dem Zusammenhang'},
{id:'v014',ru:'работать',de:'arbeiten',type:'verb',topic:'Alltag'},
{id:'v015',ru:'жить',de:'leben',altDe:['wohnen'],type:'verb',topic:'Alltag'},
{id:'v016',ru:'учиться',de:'lernen',altDe:['studieren'],type:'verb',topic:'Alltag'},
{id:'v017',ru:'читать',de:'lesen',type:'verb',topic:'Alltag'},
{id:'v018',ru:'писать',de:'schreiben',type:'verb',topic:'Alltag'},
{id:'v019',ru:'говорить',de:'sprechen',altDe:['reden','sagen'],type:'verb',topic:'Alltag'},
{id:'v020',ru:'смотреть',de:'ansehen',altDe:['schauen','sehen'],type:'verb',topic:'Alltag'},
{id:'v021',ru:'посмотреть',de:'ansehen',altDe:['anschauen'],type:'verb',topic:'Alltag',note:'vollendet'},
{id:'v022',ru:'любить',de:'lieben',altDe:['gern haben','gern machen'],type:'verb',topic:'Alltag'},
{id:'v023',ru:'хотеть',de:'wollen',altDe:['möchten'],type:'verb',topic:'Alltag'},
{id:'v024',ru:'мочь',de:'können',type:'verb',topic:'Alltag'},
{id:'v025',ru:'есть',de:'essen',type:'verb',topic:'Alltag'},
{id:'v026',ru:'пить',de:'trinken',type:'verb',topic:'Alltag'},
{id:'v027',ru:'покупать',de:'kaufen',type:'verb',topic:'Alltag'},
{id:'v028',ru:'делать',de:'machen',altDe:['tun'],type:'verb',topic:'Alltag'},
{id:'v029',ru:'играть',de:'spielen',type:'verb',topic:'Freizeit'},
{id:'v030',ru:'отдыхать',de:'sich erholen',altDe:['Urlaub machen','ausruhen'],type:'verb',topic:'Reisen'},
{id:'v031',ru:'путешествовать',de:'reisen',type:'verb',topic:'Reisen'},
{id:'v032',ru:'парк',de:'Park',type:'noun',topic:'Orte'},
{id:'v033',ru:'кафе',de:'Café',altDe:['Cafe'],type:'noun',topic:'Orte'},
{id:'v034',ru:'кино',de:'Kino',type:'noun',topic:'Orte'},
{id:'v035',ru:'музей',de:'Museum',type:'noun',topic:'Orte'},
{id:'v036',ru:'вокзал',de:'Bahnhof',type:'noun',topic:'Orte'},
{id:'v037',ru:'супермаркет',de:'Supermarkt',type:'noun',topic:'Orte'},
{id:'v038',ru:'врач',de:'Arzt',type:'noun',topic:'Menschen'},
{id:'v039',ru:'работа',de:'Arbeit',type:'noun',topic:'Alltag'},
{id:'v040',ru:'дом',de:'Haus',altDe:['zu Hause'],type:'noun',topic:'Alltag'},
{id:'v041',ru:'семья',de:'Familie',type:'noun',topic:'Familie'},
{id:'v042',ru:'сын',de:'Sohn',type:'noun',topic:'Familie'},
{id:'v043',ru:'дочь',de:'Tochter',type:'noun',topic:'Familie'},
{id:'v044',ru:'сестра',de:'Schwester',type:'noun',topic:'Familie'},
{id:'v045',ru:'дети',de:'Kinder',type:'noun',topic:'Familie'},
{id:'v046',ru:'друг',de:'Freund',type:'noun',topic:'Menschen'},
{id:'v047',ru:'сегодня',de:'heute',type:'adverb',topic:'Zeit'},
{id:'v048',ru:'завтра',de:'morgen',type:'adverb',topic:'Zeit'},
{id:'v049',ru:'вчера',de:'gestern',type:'adverb',topic:'Zeit'},
{id:'v050',ru:'каждый день',de:'jeden Tag',type:'phrase',topic:'Zeit'},
{id:'v051',ru:'каждый понедельник',de:'jeden Montag',type:'phrase',topic:'Zeit'},
{id:'v052',ru:'каждую пятницу',de:'jeden Freitag',type:'phrase',topic:'Zeit'},
{id:'v053',ru:'снова',de:'wieder',altDe:['erneut'],type:'adverb',topic:'Alltag'},
{id:'v054',ru:'опять',de:'wieder',altDe:['noch einmal'],type:'adverb',topic:'Alltag'},
{id:'v055',ru:'там',de:'dort',type:'adverb',topic:'Alltag'},
{id:'v056',ru:'здесь',de:'hier',type:'adverb',topic:'Alltag'},
{id:'v057',ru:'потому что',de:'weil',type:'phrase',topic:'Verknüpfungen'},
{id:'v058',ru:'но',de:'aber',type:'other',topic:'Verknüpfungen'},
{id:'v059',ru:'тоже',de:'auch',type:'adverb',topic:'Verknüpfungen'},
{id:'v060',ru:'тёплый',de:'warm',type:'adjective',topic:'Wetter'},
{id:'v061',ru:'плохой',de:'schlecht',type:'adjective',topic:'Alltag'},
{id:'v062',ru:'хороший',de:'gut',type:'adjective',topic:'Alltag'},
{id:'v063',ru:'погода',de:'Wetter',type:'noun',topic:'Wetter'},
{id:'v064',ru:'солнце',de:'Sonne',type:'noun',topic:'Wetter'},
{id:'v065',ru:'пляж',de:'Strand',type:'noun',topic:'Reisen'},
{id:'v066',ru:'море',de:'Meer',type:'noun',topic:'Reisen'},
{id:'v067',ru:'вода',de:'Wasser',type:'noun',topic:'Reisen'},
{id:'v068',ru:'еда',de:'Essen',altDe:['Nahrung'],type:'noun',topic:'Alltag'},
{id:'v069',ru:'подарок',de:'Geschenk',type:'noun',topic:'Familie'},
{id:'v070',ru:'лошадь',de:'Pferd',type:'noun',topic:'Tiere'},
{id:'v071',ru:'собака',de:'Hund',type:'noun',topic:'Tiere'},
{id:'v072',ru:'обезьяна',de:'Affe',type:'noun',topic:'Tiere'},
{id:'v073',ru:'птица',de:'Vogel',type:'noun',topic:'Tiere'},
{id:'v074',ru:'коза',de:'Ziege',type:'noun',topic:'Tiere'},
{id:'v075',ru:'кенгуру',de:'Känguru',altDe:['Kaenguru'],type:'noun',topic:'Tiere'},
{id:'v076',ru:'участок',de:'Grundstück',altDe:['Grundstueck'],type:'noun',topic:'Haus'},
{id:'v077',ru:'электричество',de:'Strom',altDe:['Elektrizität','Elektrizitaet'],type:'noun',topic:'Umwelt'},
{id:'v078',ru:'радиатор',de:'Heizkörper',altDe:['Heizkoerper','Radiator'],type:'noun',topic:'Umwelt'},
{id:'v079',ru:'мусор',de:'Müll',altDe:['Muell','Abfall'],type:'noun',topic:'Umwelt'},
{id:'v080',ru:'машина',de:'Auto',altDe:['Wagen'],type:'noun',topic:'Alltag'}
];
